version: "3"

services:
  nginx:
    build: ./nginx_docker
    depends_on:
      - api
    ports:
      - "8069:80"
  traefik:
    somehow:
      - load api1://8000
      - load ap2://8000
  api1:
    image: api
    ports:
      - 8001:8000
  api2:
    image: api
    ports:
      - 8002:8000
  api:
    build: .
    depends_on:
      - postgres__
    ports:
      - "8002:8000"
      - "8003:8001"
    env_file:
      - ./app/.env
    environment:
      - DATABASE_HOSTNAME=postgres__
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=meomeo
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=50753f7b75aaff03a82e96c8eed87b7e3325bb46de1def9df11fc2c2d411108a
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10
  postgres__:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=meomeo
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: